"""
Action objects and registries for GAME agents.

This module defines the "A" in GAME. An ``Action`` wraps a normal Python
function and describes it in a way the model can understand. The
``ActionRegistry`` stores the actions available to a specific agent.

Typical use:
    from game import Action, ActionRegistry

    def list_files() -> list[str]:
        return ["README.md", "main.py"]

    registry = ActionRegistry()
    registry.register(Action(
        name="list_files",
        function=list_files,
        description="Return the files in the current project.",
        parameters={"type": "object", "properties": {}, "required": []},
    ))

In most exercises, you do not edit this file. You create action functions
in the copied agent file and register them with ``ActionRegistry``.
"""

from __future__ import annotations

from typing import Any, Callable, Dict, List, Optional


class Action:
    """
    Represents one tool the agent can choose.

    Args:
        name: Tool name the model must use in its JSON response.
        function: Python callable executed when the action is selected.
        description: Explanation shown to the model in the prompt.
        parameters: JSON-schema-like description of expected arguments.
        terminal: Whether this action should stop the agent loop.

    Example:
        def echo(message: str) -> str:
            return message

        action = Action(
            name="echo",
            function=echo,
            description="Return the provided message.",
            parameters={
                "type": "object",
                "properties": {"message": {"type": "string"}},
                "required": ["message"],
            },
        )
    """

    def __init__(
        self,
        name: str,
        function: Callable[..., Any],
        description: str,
        parameters: Optional[Dict[str, Any]] = None,
        terminal: bool = False,
    ) -> None:
        self.name = name
        self.function = function
        self.description = description
        self.parameters = parameters or {
            "type": "object",
            "properties": {},
            "required": [],
        }
        self.terminal = terminal

    def validate_args(self, args: Dict[str, Any]) -> None:
        """
        Validate action arguments using a small JSON-schema-like subset.

        This method intentionally stays lightweight for students. It checks
        that required fields are present and that no unexpected argument is
        passed when ``properties`` is defined. More advanced projects can
        replace this with the ``jsonschema`` package.

        Args:
            args: Parsed arguments requested by the model.

        Raises:
            ValueError: If required arguments are missing or unknown
                arguments are provided.
        """
        properties = self.parameters.get("properties", {})
        required = self.parameters.get("required", [])

        missing = [name for name in required if name not in args]
        if missing:
            raise ValueError(
                f"Missing required argument(s) for action '{self.name}': "
                f"{', '.join(missing)}"
            )

        if properties:
            unknown = [name for name in args if name not in properties]
            if unknown:
                raise ValueError(
                    f"Unknown argument(s) for action '{self.name}': "
                    f"{', '.join(unknown)}"
                )

    def execute(self, **args: Any) -> Any:
        """
        Execute the wrapped Python function.

        Args:
            **args: Keyword arguments passed to the action function.

        Returns:
            Whatever the wrapped function returns.
        """
        self.validate_args(args)
        return self.function(**args)

    def to_prompt_schema(self) -> Dict[str, Any]:
        """
        Return the action metadata used inside the model prompt.

        Returns:
            A dictionary containing name, description, parameters, and
            terminal status.
        """
        return {
            "name": self.name,
            "description": self.description,
            "parameters": self.parameters,
            "terminal": self.terminal,
        }


class ActionRegistry:
    """
    Stores the actions available to an agent.

    The model returns an action name, and the registry finds the matching
    ``Action`` object.
    """

    def __init__(self) -> None:
        self._actions: Dict[str, Action] = {}

    def register(self, action: Action) -> None:
        """
        Add an action to the registry.

        Args:
            action: The ``Action`` object to make available to the agent.

        Raises:
            ValueError: If another action with the same name already exists.
        """
        if action.name in self._actions:
            raise ValueError(f"Action already registered: {action.name}")

        self._actions[action.name] = action

    def get_action(self, name: str) -> Optional[Action]:
        """
        Return an action by name.

        Args:
            name: Action name requested by the model.

        Returns:
            The matching ``Action`` or ``None`` if no action exists.
        """
        return self._actions.get(name)

    def get_actions(self) -> List[Action]:
        """
        Return all registered actions.

        Returns:
            A list of actions used to build the prompt.
        """
        return list(self._actions.values())
