"""
Goal objects for GAME agents.

This module defines the ``Goal`` data structure used by the prompt builder.
Goals are the "G" in GAME. They describe what the agent should accomplish
and which behavior should guide its decisions.

Typical use:
    from game import Goal

    goals = [
        Goal(
            priority=1,
            name="Explore project files",
            description="List files before reading specific files.",
        ),
        Goal(
            priority=2,
            name="Stop when complete",
            description="Use the terminal action when the task is done.",
        ),
    ]

In most exercises, you do not edit this file. You import ``Goal`` and create
new goal objects in the copied agent file.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Goal:
    """
    Represents one goal or instruction for the agent.

    Goals are included in the prompt and guide how the model chooses the
    next action.

    Args:
        priority: Lower numbers are shown first in the prompt.
        name: Short human-readable name for the goal.
        description: Detailed instruction for the model.

    Example:
        goal = Goal(
            priority=1,
            name="Explore project files",
            description="List files before reading any specific file.",
        )
    """

    priority: int
    name: str
    description: str
